/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as UsersRouteImport } from './routes/users'
import { Route as OaResultAssessmentIdUserIdRouteImport } from './routes/oa-result.$assessmentId.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OaResultAssessmentIdUserIdRoute =
  OaResultAssessmentIdUserIdRouteImport.update({
    id: '/oa-result/$assessmentId/$userId',
    path: '/oa-result/$assessmentId/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/assessments': typeof AssessmentsRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/courses': typeof CoursesRoute
  '/internships': typeof InternshipsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/users': typeof UsersRoute
  '/oa-result/$assessmentId/$userId': typeof OaResultAssessmentIdUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/assessments': typeof AssessmentsRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/courses': typeof CoursesRoute
  '/internships': typeof InternshipsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/users': typeof UsersRoute
  '/oa-result/$assessmentId/$userId': typeof OaResultAssessmentIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/assessments': typeof AssessmentsRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/courses': typeof CoursesRoute
  '/internships': typeof InternshipsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/users': typeof UsersRoute
  '/oa-result/$assessmentId/$userId': typeof OaResultAssessmentIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/assessments'
    | '/blogs'
    | '/careers'
    | '/courses'
    | '/internships'
    | '/settings'
    | '/shop'
    | '/users'
    | '/oa-result/$assessmentId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/assessments'
    | '/blogs'
    | '/careers'
    | '/courses'
    | '/internships'
    | '/settings'
    | '/shop'
    | '/users'
    | '/oa-result/$assessmentId/$userId'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/assessments'
    | '/blogs'
    | '/careers'
    | '/courses'
    | '/internships'
    | '/settings'
    | '/shop'
    | '/users'
    | '/oa-result/$assessmentId/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRoute
  CoursesRoute: typeof CoursesRoute
  InternshipsRoute: typeof InternshipsRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  UsersRoute: typeof UsersRoute
  OaResultAssessmentIdUserIdRoute: typeof OaResultAssessmentIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oa-result/$assessmentId/$userId': {
      id: '/oa-result/$assessmentId/$userId'
      path: '/oa-result/$assessmentId/$userId'
      fullPath: '/oa-result/$assessmentId/$userId'
      preLoaderRoute: typeof OaResultAssessmentIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AssessmentsRoute: AssessmentsRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRoute,
  CoursesRoute: CoursesRoute,
  InternshipsRoute: InternshipsRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  UsersRoute: UsersRoute,
  OaResultAssessmentIdUserIdRoute: OaResultAssessmentIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
