/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as InternshipRouteImport } from './routes/internship'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin-dashboard'
import { Route as AuthenticatedLearnerDashboardRouteImport } from './routes/_authenticated/learner-dashboard'
import { Route as CertificateCertificateIdRouteImport } from './routes/certificate.$certificateId'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as TrainingsIndexRouteImport } from './routes/trainings.index'
import { Route as TrainingsSlugRouteImport } from './routes/trainings.$slug'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify.$certificateId'
import { Route as AdminAdminDashboardIndexRouteImport } from './routes/_admin/admin-dashboard.index'
import { Route as AdminAdminDashboardApplicationsRouteImport } from './routes/_admin/admin-dashboard.applications'
import { Route as AdminAdminDashboardCareersRouteImport } from './routes/_admin/admin-dashboard.careers'
import { Route as AdminAdminDashboardCoursesRouteImport } from './routes/_admin/admin-dashboard.courses'
import { Route as AdminAdminDashboardInternshipsRouteImport } from './routes/_admin/admin-dashboard.internships'
import { Route as AdminAdminDashboardShopRouteImport } from './routes/_admin/admin-dashboard.shop'
import { Route as AdminAdminDashboardTrainingsRouteImport } from './routes/_admin/admin-dashboard.trainings'
import { Route as AdminAdminDashboardUsersRouteImport } from './routes/_admin/admin-dashboard.users'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'
import { Route as AdminAdminDashboardCareersIndexRouteImport } from './routes/_admin/admin-dashboard.careers.index'
import { Route as AdminAdminDashboardCareersIdRouteImport } from './routes/_admin/admin-dashboard.careers.$id'
import { Route as AdminAdminDashboardCareersNewRouteImport } from './routes/_admin/admin-dashboard.careers.new'
import { Route as AdminAdminDashboardCoursesIndexRouteImport } from './routes/_admin/admin-dashboard.courses.index'
import { Route as AdminAdminDashboardCoursesIdRouteImport } from './routes/_admin/admin-dashboard.courses.$id'
import { Route as AdminAdminDashboardCoursesNewRouteImport } from './routes/_admin/admin-dashboard.courses.new'
import { Route as AdminAdminDashboardInternshipsIndexRouteImport } from './routes/_admin/admin-dashboard.internships.index'
import { Route as AdminAdminDashboardInternshipsIdRouteImport } from './routes/_admin/admin-dashboard.internships.$id'
import { Route as AdminAdminDashboardInternshipsNewRouteImport } from './routes/_admin/admin-dashboard.internships.new'
import { Route as AdminAdminDashboardShopIndexRouteImport } from './routes/_admin/admin-dashboard.shop.index'
import { Route as AdminAdminDashboardShopIdRouteImport } from './routes/_admin/admin-dashboard.shop.$id'
import { Route as AdminAdminDashboardShopNewRouteImport } from './routes/_admin/admin-dashboard.shop.new'
import { Route as AdminAdminDashboardShopOrdersRouteImport } from './routes/_admin/admin-dashboard.shop.orders'
import { Route as AdminAdminDashboardTrainingsIndexRouteImport } from './routes/_admin/admin-dashboard.trainings.index'
import { Route as AdminAdminDashboardTrainingsIdRouteImport } from './routes/_admin/admin-dashboard.trainings.$id'
import { Route as AdminAdminDashboardTrainingsNewRouteImport } from './routes/_admin/admin-dashboard.trainings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipRoute = InternshipRouteImport.update({
  id: '/internship',
  path: '/internship',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedLearnerDashboardRoute =
  AuthenticatedLearnerDashboardRouteImport.update({
    id: '/learner-dashboard',
    path: '/learner-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CertificateCertificateIdRoute =
  CertificateCertificateIdRouteImport.update({
    id: '/certificate/$certificateId',
    path: '/certificate/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const TrainingsIndexRoute = TrainingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingsRoute,
} as any)
const TrainingsSlugRoute = TrainingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrainingsRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardIndexRoute =
  AdminAdminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardApplicationsRoute =
  AdminAdminDashboardApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardCareersRoute =
  AdminAdminDashboardCareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardCoursesRoute =
  AdminAdminDashboardCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardInternshipsRoute =
  AdminAdminDashboardInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardShopRoute = AdminAdminDashboardShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminAdminDashboardRoute,
} as any)
const AdminAdminDashboardTrainingsRoute =
  AdminAdminDashboardTrainingsRouteImport.update({
    id: '/trainings',
    path: '/trainings',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardUsersRoute =
  AdminAdminDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAdminDashboardCareersIndexRoute =
  AdminAdminDashboardCareersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardCareersRoute,
  } as any)
const AdminAdminDashboardCareersIdRoute =
  AdminAdminDashboardCareersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardCareersRoute,
  } as any)
const AdminAdminDashboardCareersNewRoute =
  AdminAdminDashboardCareersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminDashboardCareersRoute,
  } as any)
const AdminAdminDashboardCoursesIndexRoute =
  AdminAdminDashboardCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardCoursesRoute,
  } as any)
const AdminAdminDashboardCoursesIdRoute =
  AdminAdminDashboardCoursesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardCoursesRoute,
  } as any)
const AdminAdminDashboardCoursesNewRoute =
  AdminAdminDashboardCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminDashboardCoursesRoute,
  } as any)
const AdminAdminDashboardInternshipsIndexRoute =
  AdminAdminDashboardInternshipsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardInternshipsRoute,
  } as any)
const AdminAdminDashboardInternshipsIdRoute =
  AdminAdminDashboardInternshipsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardInternshipsRoute,
  } as any)
const AdminAdminDashboardInternshipsNewRoute =
  AdminAdminDashboardInternshipsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminDashboardInternshipsRoute,
  } as any)
const AdminAdminDashboardShopIndexRoute =
  AdminAdminDashboardShopIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardShopRoute,
  } as any)
const AdminAdminDashboardShopIdRoute =
  AdminAdminDashboardShopIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardShopRoute,
  } as any)
const AdminAdminDashboardShopNewRoute =
  AdminAdminDashboardShopNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminDashboardShopRoute,
  } as any)
const AdminAdminDashboardShopOrdersRoute =
  AdminAdminDashboardShopOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AdminAdminDashboardShopRoute,
  } as any)
const AdminAdminDashboardTrainingsIndexRoute =
  AdminAdminDashboardTrainingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardTrainingsRoute,
  } as any)
const AdminAdminDashboardTrainingsIdRoute =
  AdminAdminDashboardTrainingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardTrainingsRoute,
  } as any)
const AdminAdminDashboardTrainingsNewRoute =
  AdminAdminDashboardTrainingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminDashboardTrainingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/courses': typeof CoursesRouteWithChildren
  '/internship': typeof InternshipRoute
  '/shop': typeof ShopRouteWithChildren
  '/trainings': typeof TrainingsRouteWithChildren
  '/admin-dashboard': typeof AdminAdminDashboardRouteWithChildren
  '/learner-dashboard': typeof AuthenticatedLearnerDashboardRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin-dashboard/applications': typeof AdminAdminDashboardApplicationsRoute
  '/admin-dashboard/careers': typeof AdminAdminDashboardCareersRouteWithChildren
  '/admin-dashboard/courses': typeof AdminAdminDashboardCoursesRouteWithChildren
  '/admin-dashboard/internships': typeof AdminAdminDashboardInternshipsRouteWithChildren
  '/admin-dashboard/shop': typeof AdminAdminDashboardShopRouteWithChildren
  '/admin-dashboard/trainings': typeof AdminAdminDashboardTrainingsRouteWithChildren
  '/admin-dashboard/users': typeof AdminAdminDashboardUsersRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/admin-dashboard/': typeof AdminAdminDashboardIndexRoute
  '/admin-dashboard/careers/$id': typeof AdminAdminDashboardCareersIdRoute
  '/admin-dashboard/careers/new': typeof AdminAdminDashboardCareersNewRoute
  '/admin-dashboard/courses/$id': typeof AdminAdminDashboardCoursesIdRoute
  '/admin-dashboard/courses/new': typeof AdminAdminDashboardCoursesNewRoute
  '/admin-dashboard/internships/$id': typeof AdminAdminDashboardInternshipsIdRoute
  '/admin-dashboard/internships/new': typeof AdminAdminDashboardInternshipsNewRoute
  '/admin-dashboard/shop/$id': typeof AdminAdminDashboardShopIdRoute
  '/admin-dashboard/shop/new': typeof AdminAdminDashboardShopNewRoute
  '/admin-dashboard/shop/orders': typeof AdminAdminDashboardShopOrdersRoute
  '/admin-dashboard/trainings/$id': typeof AdminAdminDashboardTrainingsIdRoute
  '/admin-dashboard/trainings/new': typeof AdminAdminDashboardTrainingsNewRoute
  '/admin-dashboard/careers/': typeof AdminAdminDashboardCareersIndexRoute
  '/admin-dashboard/courses/': typeof AdminAdminDashboardCoursesIndexRoute
  '/admin-dashboard/internships/': typeof AdminAdminDashboardInternshipsIndexRoute
  '/admin-dashboard/shop/': typeof AdminAdminDashboardShopIndexRoute
  '/admin-dashboard/trainings/': typeof AdminAdminDashboardTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/internship': typeof InternshipRoute
  '/learner-dashboard': typeof AuthenticatedLearnerDashboardRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/courses': typeof CoursesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/trainings': typeof TrainingsIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/admin-dashboard/applications': typeof AdminAdminDashboardApplicationsRoute
  '/admin-dashboard/users': typeof AdminAdminDashboardUsersRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/admin-dashboard': typeof AdminAdminDashboardIndexRoute
  '/admin-dashboard/careers/$id': typeof AdminAdminDashboardCareersIdRoute
  '/admin-dashboard/careers/new': typeof AdminAdminDashboardCareersNewRoute
  '/admin-dashboard/courses/$id': typeof AdminAdminDashboardCoursesIdRoute
  '/admin-dashboard/courses/new': typeof AdminAdminDashboardCoursesNewRoute
  '/admin-dashboard/internships/$id': typeof AdminAdminDashboardInternshipsIdRoute
  '/admin-dashboard/internships/new': typeof AdminAdminDashboardInternshipsNewRoute
  '/admin-dashboard/shop/$id': typeof AdminAdminDashboardShopIdRoute
  '/admin-dashboard/shop/new': typeof AdminAdminDashboardShopNewRoute
  '/admin-dashboard/shop/orders': typeof AdminAdminDashboardShopOrdersRoute
  '/admin-dashboard/trainings/$id': typeof AdminAdminDashboardTrainingsIdRoute
  '/admin-dashboard/trainings/new': typeof AdminAdminDashboardTrainingsNewRoute
  '/admin-dashboard/careers': typeof AdminAdminDashboardCareersIndexRoute
  '/admin-dashboard/courses': typeof AdminAdminDashboardCoursesIndexRoute
  '/admin-dashboard/internships': typeof AdminAdminDashboardInternshipsIndexRoute
  '/admin-dashboard/shop': typeof AdminAdminDashboardShopIndexRoute
  '/admin-dashboard/trainings': typeof AdminAdminDashboardTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/courses': typeof CoursesRouteWithChildren
  '/internship': typeof InternshipRoute
  '/shop': typeof ShopRouteWithChildren
  '/trainings': typeof TrainingsRouteWithChildren
  '/_admin/admin-dashboard': typeof AdminAdminDashboardRouteWithChildren
  '/_authenticated/learner-dashboard': typeof AuthenticatedLearnerDashboardRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/_admin/admin-dashboard/applications': typeof AdminAdminDashboardApplicationsRoute
  '/_admin/admin-dashboard/careers': typeof AdminAdminDashboardCareersRouteWithChildren
  '/_admin/admin-dashboard/courses': typeof AdminAdminDashboardCoursesRouteWithChildren
  '/_admin/admin-dashboard/internships': typeof AdminAdminDashboardInternshipsRouteWithChildren
  '/_admin/admin-dashboard/shop': typeof AdminAdminDashboardShopRouteWithChildren
  '/_admin/admin-dashboard/trainings': typeof AdminAdminDashboardTrainingsRouteWithChildren
  '/_admin/admin-dashboard/users': typeof AdminAdminDashboardUsersRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_admin/admin-dashboard/': typeof AdminAdminDashboardIndexRoute
  '/_admin/admin-dashboard/careers/$id': typeof AdminAdminDashboardCareersIdRoute
  '/_admin/admin-dashboard/careers/new': typeof AdminAdminDashboardCareersNewRoute
  '/_admin/admin-dashboard/courses/$id': typeof AdminAdminDashboardCoursesIdRoute
  '/_admin/admin-dashboard/courses/new': typeof AdminAdminDashboardCoursesNewRoute
  '/_admin/admin-dashboard/internships/$id': typeof AdminAdminDashboardInternshipsIdRoute
  '/_admin/admin-dashboard/internships/new': typeof AdminAdminDashboardInternshipsNewRoute
  '/_admin/admin-dashboard/shop/$id': typeof AdminAdminDashboardShopIdRoute
  '/_admin/admin-dashboard/shop/new': typeof AdminAdminDashboardShopNewRoute
  '/_admin/admin-dashboard/shop/orders': typeof AdminAdminDashboardShopOrdersRoute
  '/_admin/admin-dashboard/trainings/$id': typeof AdminAdminDashboardTrainingsIdRoute
  '/_admin/admin-dashboard/trainings/new': typeof AdminAdminDashboardTrainingsNewRoute
  '/_admin/admin-dashboard/careers/': typeof AdminAdminDashboardCareersIndexRoute
  '/_admin/admin-dashboard/courses/': typeof AdminAdminDashboardCoursesIndexRoute
  '/_admin/admin-dashboard/internships/': typeof AdminAdminDashboardInternshipsIndexRoute
  '/_admin/admin-dashboard/shop/': typeof AdminAdminDashboardShopIndexRoute
  '/_admin/admin-dashboard/trainings/': typeof AdminAdminDashboardTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/careers'
    | '/courses'
    | '/internship'
    | '/shop'
    | '/trainings'
    | '/admin-dashboard'
    | '/learner-dashboard'
    | '/certificate/$certificateId'
    | '/courses/$slug'
    | '/shop/$slug'
    | '/trainings/$slug'
    | '/verify/$certificateId'
    | '/courses/'
    | '/shop/'
    | '/trainings/'
    | '/verify/'
    | '/admin-dashboard/applications'
    | '/admin-dashboard/careers'
    | '/admin-dashboard/courses'
    | '/admin-dashboard/internships'
    | '/admin-dashboard/shop'
    | '/admin-dashboard/trainings'
    | '/admin-dashboard/users'
    | '/learn/$slug'
    | '/admin-dashboard/'
    | '/admin-dashboard/careers/$id'
    | '/admin-dashboard/careers/new'
    | '/admin-dashboard/courses/$id'
    | '/admin-dashboard/courses/new'
    | '/admin-dashboard/internships/$id'
    | '/admin-dashboard/internships/new'
    | '/admin-dashboard/shop/$id'
    | '/admin-dashboard/shop/new'
    | '/admin-dashboard/shop/orders'
    | '/admin-dashboard/trainings/$id'
    | '/admin-dashboard/trainings/new'
    | '/admin-dashboard/careers/'
    | '/admin-dashboard/courses/'
    | '/admin-dashboard/internships/'
    | '/admin-dashboard/shop/'
    | '/admin-dashboard/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/careers'
    | '/internship'
    | '/learner-dashboard'
    | '/certificate/$certificateId'
    | '/courses/$slug'
    | '/shop/$slug'
    | '/trainings/$slug'
    | '/verify/$certificateId'
    | '/courses'
    | '/shop'
    | '/trainings'
    | '/verify'
    | '/admin-dashboard/applications'
    | '/admin-dashboard/users'
    | '/learn/$slug'
    | '/admin-dashboard'
    | '/admin-dashboard/careers/$id'
    | '/admin-dashboard/careers/new'
    | '/admin-dashboard/courses/$id'
    | '/admin-dashboard/courses/new'
    | '/admin-dashboard/internships/$id'
    | '/admin-dashboard/internships/new'
    | '/admin-dashboard/shop/$id'
    | '/admin-dashboard/shop/new'
    | '/admin-dashboard/shop/orders'
    | '/admin-dashboard/trainings/$id'
    | '/admin-dashboard/trainings/new'
    | '/admin-dashboard/careers'
    | '/admin-dashboard/courses'
    | '/admin-dashboard/internships'
    | '/admin-dashboard/shop'
    | '/admin-dashboard/trainings'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/careers'
    | '/courses'
    | '/internship'
    | '/shop'
    | '/trainings'
    | '/_admin/admin-dashboard'
    | '/_authenticated/learner-dashboard'
    | '/certificate/$certificateId'
    | '/courses/$slug'
    | '/shop/$slug'
    | '/trainings/$slug'
    | '/verify/$certificateId'
    | '/courses/'
    | '/shop/'
    | '/trainings/'
    | '/verify/'
    | '/_admin/admin-dashboard/applications'
    | '/_admin/admin-dashboard/careers'
    | '/_admin/admin-dashboard/courses'
    | '/_admin/admin-dashboard/internships'
    | '/_admin/admin-dashboard/shop'
    | '/_admin/admin-dashboard/trainings'
    | '/_admin/admin-dashboard/users'
    | '/_authenticated/learn/$slug'
    | '/_admin/admin-dashboard/'
    | '/_admin/admin-dashboard/careers/$id'
    | '/_admin/admin-dashboard/careers/new'
    | '/_admin/admin-dashboard/courses/$id'
    | '/_admin/admin-dashboard/courses/new'
    | '/_admin/admin-dashboard/internships/$id'
    | '/_admin/admin-dashboard/internships/new'
    | '/_admin/admin-dashboard/shop/$id'
    | '/_admin/admin-dashboard/shop/new'
    | '/_admin/admin-dashboard/shop/orders'
    | '/_admin/admin-dashboard/trainings/$id'
    | '/_admin/admin-dashboard/trainings/new'
    | '/_admin/admin-dashboard/careers/'
    | '/_admin/admin-dashboard/courses/'
    | '/_admin/admin-dashboard/internships/'
    | '/_admin/admin-dashboard/shop/'
    | '/_admin/admin-dashboard/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  InternshipRoute: typeof InternshipRoute
  ShopRoute: typeof ShopRouteWithChildren
  TrainingsRoute: typeof TrainingsRouteWithChildren
  CertificateCertificateIdRoute: typeof CertificateCertificateIdRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship': {
      id: '/internship'
      path: '/internship'
      fullPath: '/internship'
      preLoaderRoute: typeof InternshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin-dashboard': {
      id: '/_admin/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/learner-dashboard': {
      id: '/_authenticated/learner-dashboard'
      path: '/learner-dashboard'
      fullPath: '/learner-dashboard'
      preLoaderRoute: typeof AuthenticatedLearnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificate/$certificateId': {
      id: '/certificate/$certificateId'
      path: '/certificate/$certificateId'
      fullPath: '/certificate/$certificateId'
      preLoaderRoute: typeof CertificateCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/trainings/': {
      id: '/trainings/'
      path: '/'
      fullPath: '/trainings/'
      preLoaderRoute: typeof TrainingsIndexRouteImport
      parentRoute: typeof TrainingsRoute
    }
    '/trainings/$slug': {
      id: '/trainings/$slug'
      path: '/$slug'
      fullPath: '/trainings/$slug'
      preLoaderRoute: typeof TrainingsSlugRouteImport
      parentRoute: typeof TrainingsRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin-dashboard/': {
      id: '/_admin/admin-dashboard/'
      path: '/'
      fullPath: '/admin-dashboard/'
      preLoaderRoute: typeof AdminAdminDashboardIndexRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/applications': {
      id: '/_admin/admin-dashboard/applications'
      path: '/applications'
      fullPath: '/admin-dashboard/applications'
      preLoaderRoute: typeof AdminAdminDashboardApplicationsRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/careers': {
      id: '/_admin/admin-dashboard/careers'
      path: '/careers'
      fullPath: '/admin-dashboard/careers'
      preLoaderRoute: typeof AdminAdminDashboardCareersRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/courses': {
      id: '/_admin/admin-dashboard/courses'
      path: '/courses'
      fullPath: '/admin-dashboard/courses'
      preLoaderRoute: typeof AdminAdminDashboardCoursesRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/internships': {
      id: '/_admin/admin-dashboard/internships'
      path: '/internships'
      fullPath: '/admin-dashboard/internships'
      preLoaderRoute: typeof AdminAdminDashboardInternshipsRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/shop': {
      id: '/_admin/admin-dashboard/shop'
      path: '/shop'
      fullPath: '/admin-dashboard/shop'
      preLoaderRoute: typeof AdminAdminDashboardShopRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/trainings': {
      id: '/_admin/admin-dashboard/trainings'
      path: '/trainings'
      fullPath: '/admin-dashboard/trainings'
      preLoaderRoute: typeof AdminAdminDashboardTrainingsRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin-dashboard/users': {
      id: '/_admin/admin-dashboard/users'
      path: '/users'
      fullPath: '/admin-dashboard/users'
      preLoaderRoute: typeof AdminAdminDashboardUsersRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin-dashboard/careers/': {
      id: '/_admin/admin-dashboard/careers/'
      path: '/'
      fullPath: '/admin-dashboard/careers/'
      preLoaderRoute: typeof AdminAdminDashboardCareersIndexRouteImport
      parentRoute: typeof AdminAdminDashboardCareersRoute
    }
    '/_admin/admin-dashboard/careers/$id': {
      id: '/_admin/admin-dashboard/careers/$id'
      path: '/$id'
      fullPath: '/admin-dashboard/careers/$id'
      preLoaderRoute: typeof AdminAdminDashboardCareersIdRouteImport
      parentRoute: typeof AdminAdminDashboardCareersRoute
    }
    '/_admin/admin-dashboard/careers/new': {
      id: '/_admin/admin-dashboard/careers/new'
      path: '/new'
      fullPath: '/admin-dashboard/careers/new'
      preLoaderRoute: typeof AdminAdminDashboardCareersNewRouteImport
      parentRoute: typeof AdminAdminDashboardCareersRoute
    }
    '/_admin/admin-dashboard/courses/': {
      id: '/_admin/admin-dashboard/courses/'
      path: '/'
      fullPath: '/admin-dashboard/courses/'
      preLoaderRoute: typeof AdminAdminDashboardCoursesIndexRouteImport
      parentRoute: typeof AdminAdminDashboardCoursesRoute
    }
    '/_admin/admin-dashboard/courses/$id': {
      id: '/_admin/admin-dashboard/courses/$id'
      path: '/$id'
      fullPath: '/admin-dashboard/courses/$id'
      preLoaderRoute: typeof AdminAdminDashboardCoursesIdRouteImport
      parentRoute: typeof AdminAdminDashboardCoursesRoute
    }
    '/_admin/admin-dashboard/courses/new': {
      id: '/_admin/admin-dashboard/courses/new'
      path: '/new'
      fullPath: '/admin-dashboard/courses/new'
      preLoaderRoute: typeof AdminAdminDashboardCoursesNewRouteImport
      parentRoute: typeof AdminAdminDashboardCoursesRoute
    }
    '/_admin/admin-dashboard/internships/': {
      id: '/_admin/admin-dashboard/internships/'
      path: '/'
      fullPath: '/admin-dashboard/internships/'
      preLoaderRoute: typeof AdminAdminDashboardInternshipsIndexRouteImport
      parentRoute: typeof AdminAdminDashboardInternshipsRoute
    }
    '/_admin/admin-dashboard/internships/$id': {
      id: '/_admin/admin-dashboard/internships/$id'
      path: '/$id'
      fullPath: '/admin-dashboard/internships/$id'
      preLoaderRoute: typeof AdminAdminDashboardInternshipsIdRouteImport
      parentRoute: typeof AdminAdminDashboardInternshipsRoute
    }
    '/_admin/admin-dashboard/internships/new': {
      id: '/_admin/admin-dashboard/internships/new'
      path: '/new'
      fullPath: '/admin-dashboard/internships/new'
      preLoaderRoute: typeof AdminAdminDashboardInternshipsNewRouteImport
      parentRoute: typeof AdminAdminDashboardInternshipsRoute
    }
    '/_admin/admin-dashboard/shop/': {
      id: '/_admin/admin-dashboard/shop/'
      path: '/'
      fullPath: '/admin-dashboard/shop/'
      preLoaderRoute: typeof AdminAdminDashboardShopIndexRouteImport
      parentRoute: typeof AdminAdminDashboardShopRoute
    }
    '/_admin/admin-dashboard/shop/$id': {
      id: '/_admin/admin-dashboard/shop/$id'
      path: '/$id'
      fullPath: '/admin-dashboard/shop/$id'
      preLoaderRoute: typeof AdminAdminDashboardShopIdRouteImport
      parentRoute: typeof AdminAdminDashboardShopRoute
    }
    '/_admin/admin-dashboard/shop/new': {
      id: '/_admin/admin-dashboard/shop/new'
      path: '/new'
      fullPath: '/admin-dashboard/shop/new'
      preLoaderRoute: typeof AdminAdminDashboardShopNewRouteImport
      parentRoute: typeof AdminAdminDashboardShopRoute
    }
    '/_admin/admin-dashboard/shop/orders': {
      id: '/_admin/admin-dashboard/shop/orders'
      path: '/orders'
      fullPath: '/admin-dashboard/shop/orders'
      preLoaderRoute: typeof AdminAdminDashboardShopOrdersRouteImport
      parentRoute: typeof AdminAdminDashboardShopRoute
    }
    '/_admin/admin-dashboard/trainings/': {
      id: '/_admin/admin-dashboard/trainings/'
      path: '/'
      fullPath: '/admin-dashboard/trainings/'
      preLoaderRoute: typeof AdminAdminDashboardTrainingsIndexRouteImport
      parentRoute: typeof AdminAdminDashboardTrainingsRoute
    }
    '/_admin/admin-dashboard/trainings/$id': {
      id: '/_admin/admin-dashboard/trainings/$id'
      path: '/$id'
      fullPath: '/admin-dashboard/trainings/$id'
      preLoaderRoute: typeof AdminAdminDashboardTrainingsIdRouteImport
      parentRoute: typeof AdminAdminDashboardTrainingsRoute
    }
    '/_admin/admin-dashboard/trainings/new': {
      id: '/_admin/admin-dashboard/trainings/new'
      path: '/new'
      fullPath: '/admin-dashboard/trainings/new'
      preLoaderRoute: typeof AdminAdminDashboardTrainingsNewRouteImport
      parentRoute: typeof AdminAdminDashboardTrainingsRoute
    }
  }
}

interface AdminAdminDashboardCareersRouteChildren {
  AdminAdminDashboardCareersIdRoute: typeof AdminAdminDashboardCareersIdRoute
  AdminAdminDashboardCareersNewRoute: typeof AdminAdminDashboardCareersNewRoute
  AdminAdminDashboardCareersIndexRoute: typeof AdminAdminDashboardCareersIndexRoute
}

const AdminAdminDashboardCareersRouteChildren: AdminAdminDashboardCareersRouteChildren =
  {
    AdminAdminDashboardCareersIdRoute: AdminAdminDashboardCareersIdRoute,
    AdminAdminDashboardCareersNewRoute: AdminAdminDashboardCareersNewRoute,
    AdminAdminDashboardCareersIndexRoute: AdminAdminDashboardCareersIndexRoute,
  }

const AdminAdminDashboardCareersRouteWithChildren =
  AdminAdminDashboardCareersRoute._addFileChildren(
    AdminAdminDashboardCareersRouteChildren,
  )

interface AdminAdminDashboardCoursesRouteChildren {
  AdminAdminDashboardCoursesIdRoute: typeof AdminAdminDashboardCoursesIdRoute
  AdminAdminDashboardCoursesNewRoute: typeof AdminAdminDashboardCoursesNewRoute
  AdminAdminDashboardCoursesIndexRoute: typeof AdminAdminDashboardCoursesIndexRoute
}

const AdminAdminDashboardCoursesRouteChildren: AdminAdminDashboardCoursesRouteChildren =
  {
    AdminAdminDashboardCoursesIdRoute: AdminAdminDashboardCoursesIdRoute,
    AdminAdminDashboardCoursesNewRoute: AdminAdminDashboardCoursesNewRoute,
    AdminAdminDashboardCoursesIndexRoute: AdminAdminDashboardCoursesIndexRoute,
  }

const AdminAdminDashboardCoursesRouteWithChildren =
  AdminAdminDashboardCoursesRoute._addFileChildren(
    AdminAdminDashboardCoursesRouteChildren,
  )

interface AdminAdminDashboardInternshipsRouteChildren {
  AdminAdminDashboardInternshipsIdRoute: typeof AdminAdminDashboardInternshipsIdRoute
  AdminAdminDashboardInternshipsNewRoute: typeof AdminAdminDashboardInternshipsNewRoute
  AdminAdminDashboardInternshipsIndexRoute: typeof AdminAdminDashboardInternshipsIndexRoute
}

const AdminAdminDashboardInternshipsRouteChildren: AdminAdminDashboardInternshipsRouteChildren =
  {
    AdminAdminDashboardInternshipsIdRoute:
      AdminAdminDashboardInternshipsIdRoute,
    AdminAdminDashboardInternshipsNewRoute:
      AdminAdminDashboardInternshipsNewRoute,
    AdminAdminDashboardInternshipsIndexRoute:
      AdminAdminDashboardInternshipsIndexRoute,
  }

const AdminAdminDashboardInternshipsRouteWithChildren =
  AdminAdminDashboardInternshipsRoute._addFileChildren(
    AdminAdminDashboardInternshipsRouteChildren,
  )

interface AdminAdminDashboardShopRouteChildren {
  AdminAdminDashboardShopIdRoute: typeof AdminAdminDashboardShopIdRoute
  AdminAdminDashboardShopNewRoute: typeof AdminAdminDashboardShopNewRoute
  AdminAdminDashboardShopOrdersRoute: typeof AdminAdminDashboardShopOrdersRoute
  AdminAdminDashboardShopIndexRoute: typeof AdminAdminDashboardShopIndexRoute
}

const AdminAdminDashboardShopRouteChildren: AdminAdminDashboardShopRouteChildren =
  {
    AdminAdminDashboardShopIdRoute: AdminAdminDashboardShopIdRoute,
    AdminAdminDashboardShopNewRoute: AdminAdminDashboardShopNewRoute,
    AdminAdminDashboardShopOrdersRoute: AdminAdminDashboardShopOrdersRoute,
    AdminAdminDashboardShopIndexRoute: AdminAdminDashboardShopIndexRoute,
  }

const AdminAdminDashboardShopRouteWithChildren =
  AdminAdminDashboardShopRoute._addFileChildren(
    AdminAdminDashboardShopRouteChildren,
  )

interface AdminAdminDashboardTrainingsRouteChildren {
  AdminAdminDashboardTrainingsIdRoute: typeof AdminAdminDashboardTrainingsIdRoute
  AdminAdminDashboardTrainingsNewRoute: typeof AdminAdminDashboardTrainingsNewRoute
  AdminAdminDashboardTrainingsIndexRoute: typeof AdminAdminDashboardTrainingsIndexRoute
}

const AdminAdminDashboardTrainingsRouteChildren: AdminAdminDashboardTrainingsRouteChildren =
  {
    AdminAdminDashboardTrainingsIdRoute: AdminAdminDashboardTrainingsIdRoute,
    AdminAdminDashboardTrainingsNewRoute: AdminAdminDashboardTrainingsNewRoute,
    AdminAdminDashboardTrainingsIndexRoute:
      AdminAdminDashboardTrainingsIndexRoute,
  }

const AdminAdminDashboardTrainingsRouteWithChildren =
  AdminAdminDashboardTrainingsRoute._addFileChildren(
    AdminAdminDashboardTrainingsRouteChildren,
  )

interface AdminAdminDashboardRouteChildren {
  AdminAdminDashboardApplicationsRoute: typeof AdminAdminDashboardApplicationsRoute
  AdminAdminDashboardCareersRoute: typeof AdminAdminDashboardCareersRouteWithChildren
  AdminAdminDashboardCoursesRoute: typeof AdminAdminDashboardCoursesRouteWithChildren
  AdminAdminDashboardInternshipsRoute: typeof AdminAdminDashboardInternshipsRouteWithChildren
  AdminAdminDashboardShopRoute: typeof AdminAdminDashboardShopRouteWithChildren
  AdminAdminDashboardTrainingsRoute: typeof AdminAdminDashboardTrainingsRouteWithChildren
  AdminAdminDashboardUsersRoute: typeof AdminAdminDashboardUsersRoute
  AdminAdminDashboardIndexRoute: typeof AdminAdminDashboardIndexRoute
}

const AdminAdminDashboardRouteChildren: AdminAdminDashboardRouteChildren = {
  AdminAdminDashboardApplicationsRoute: AdminAdminDashboardApplicationsRoute,
  AdminAdminDashboardCareersRoute: AdminAdminDashboardCareersRouteWithChildren,
  AdminAdminDashboardCoursesRoute: AdminAdminDashboardCoursesRouteWithChildren,
  AdminAdminDashboardInternshipsRoute:
    AdminAdminDashboardInternshipsRouteWithChildren,
  AdminAdminDashboardShopRoute: AdminAdminDashboardShopRouteWithChildren,
  AdminAdminDashboardTrainingsRoute:
    AdminAdminDashboardTrainingsRouteWithChildren,
  AdminAdminDashboardUsersRoute: AdminAdminDashboardUsersRoute,
  AdminAdminDashboardIndexRoute: AdminAdminDashboardIndexRoute,
}

const AdminAdminDashboardRouteWithChildren =
  AdminAdminDashboardRoute._addFileChildren(AdminAdminDashboardRouteChildren)

interface AdminRouteRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLearnerDashboardRoute: typeof AuthenticatedLearnerDashboardRoute
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLearnerDashboardRoute: AuthenticatedLearnerDashboardRoute,
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface TrainingsRouteChildren {
  TrainingsSlugRoute: typeof TrainingsSlugRoute
  TrainingsIndexRoute: typeof TrainingsIndexRoute
}

const TrainingsRouteChildren: TrainingsRouteChildren = {
  TrainingsSlugRoute: TrainingsSlugRoute,
  TrainingsIndexRoute: TrainingsIndexRoute,
}

const TrainingsRouteWithChildren = TrainingsRoute._addFileChildren(
  TrainingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CoursesRoute: CoursesRouteWithChildren,
  InternshipRoute: InternshipRoute,
  ShopRoute: ShopRouteWithChildren,
  TrainingsRoute: TrainingsRouteWithChildren,
  CertificateCertificateIdRoute: CertificateCertificateIdRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
