/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as AssessmentsIdRouteImport } from './routes/assessments.$id'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsIdRouteImport } from './routes/blogs.$id'
import { Route as BlogsNewRouteImport } from './routes/blogs.new'
import { Route as CareersListingsIndexRouteImport } from './routes/careers.listings.index'
import { Route as CareersListingsIdRouteImport } from './routes/careers.listings.$id'
import { Route as CareersListingsNewRouteImport } from './routes/careers.listings.new'
import { Route as CareersSeasonsIndexRouteImport } from './routes/careers.seasons.index'
import { Route as CareersSeasonsSeasonRouteImport } from './routes/careers.seasons.$season'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsNewRoute = BlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersListingsIndexRoute = CareersListingsIndexRouteImport.update({
  id: '/careers/listings/',
  path: '/careers/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersListingsIdRoute = CareersListingsIdRouteImport.update({
  id: '/careers/listings/$id',
  path: '/careers/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersListingsNewRoute = CareersListingsNewRouteImport.update({
  id: '/careers/listings/new',
  path: '/careers/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSeasonsIndexRoute = CareersSeasonsIndexRouteImport.update({
  id: '/careers/seasons/',
  path: '/careers/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSeasonsSeasonRoute = CareersSeasonsSeasonRouteImport.update({
  id: '/careers/seasons/$season',
  path: '/careers/seasons/$season',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/settings': typeof SettingsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/blogs/new': typeof BlogsNewRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/listings/$id': typeof CareersListingsIdRoute
  '/careers/listings/new': typeof CareersListingsNewRoute
  '/careers/seasons/$season': typeof CareersSeasonsSeasonRoute
  '/careers/listings/': typeof CareersListingsIndexRoute
  '/careers/seasons/': typeof CareersSeasonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/settings': typeof SettingsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/blogs/new': typeof BlogsNewRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/careers/listings/$id': typeof CareersListingsIdRoute
  '/careers/listings/new': typeof CareersListingsNewRoute
  '/careers/seasons/$season': typeof CareersSeasonsSeasonRoute
  '/careers/listings': typeof CareersListingsIndexRoute
  '/careers/seasons': typeof CareersSeasonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/settings': typeof SettingsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/blogs/new': typeof BlogsNewRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/listings/$id': typeof CareersListingsIdRoute
  '/careers/listings/new': typeof CareersListingsNewRoute
  '/careers/seasons/$season': typeof CareersSeasonsSeasonRoute
  '/careers/listings/': typeof CareersListingsIndexRoute
  '/careers/seasons/': typeof CareersSeasonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inquiries'
    | '/settings'
    | '/assessments/$id'
    | '/assessments/new'
    | '/blogs/$id'
    | '/blogs/new'
    | '/assessments/'
    | '/blogs/'
    | '/careers/listings/$id'
    | '/careers/listings/new'
    | '/careers/seasons/$season'
    | '/careers/listings/'
    | '/careers/seasons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inquiries'
    | '/settings'
    | '/assessments/$id'
    | '/assessments/new'
    | '/blogs/$id'
    | '/blogs/new'
    | '/assessments'
    | '/blogs'
    | '/careers/listings/$id'
    | '/careers/listings/new'
    | '/careers/seasons/$season'
    | '/careers/listings'
    | '/careers/seasons'
  id:
    | '__root__'
    | '/'
    | '/inquiries'
    | '/settings'
    | '/assessments/$id'
    | '/assessments/new'
    | '/blogs/$id'
    | '/blogs/new'
    | '/assessments/'
    | '/blogs/'
    | '/careers/listings/$id'
    | '/careers/listings/new'
    | '/careers/seasons/$season'
    | '/careers/listings/'
    | '/careers/seasons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InquiriesRoute: typeof InquiriesRoute
  SettingsRoute: typeof SettingsRoute
  AssessmentsIdRoute: typeof AssessmentsIdRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  BlogsIdRoute: typeof BlogsIdRoute
  BlogsNewRoute: typeof BlogsNewRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CareersListingsIdRoute: typeof CareersListingsIdRoute
  CareersListingsNewRoute: typeof CareersListingsNewRoute
  CareersSeasonsSeasonRoute: typeof CareersSeasonsSeasonRoute
  CareersListingsIndexRoute: typeof CareersListingsIndexRoute
  CareersSeasonsIndexRoute: typeof CareersSeasonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/new': {
      id: '/blogs/new'
      path: '/blogs/new'
      fullPath: '/blogs/new'
      preLoaderRoute: typeof BlogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/listings/': {
      id: '/careers/listings/'
      path: '/careers/listings'
      fullPath: '/careers/listings/'
      preLoaderRoute: typeof CareersListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/listings/$id': {
      id: '/careers/listings/$id'
      path: '/careers/listings/$id'
      fullPath: '/careers/listings/$id'
      preLoaderRoute: typeof CareersListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/listings/new': {
      id: '/careers/listings/new'
      path: '/careers/listings/new'
      fullPath: '/careers/listings/new'
      preLoaderRoute: typeof CareersListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/seasons/': {
      id: '/careers/seasons/'
      path: '/careers/seasons'
      fullPath: '/careers/seasons/'
      preLoaderRoute: typeof CareersSeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/seasons/$season': {
      id: '/careers/seasons/$season'
      path: '/careers/seasons/$season'
      fullPath: '/careers/seasons/$season'
      preLoaderRoute: typeof CareersSeasonsSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InquiriesRoute: InquiriesRoute,
  SettingsRoute: SettingsRoute,
  AssessmentsIdRoute: AssessmentsIdRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
  BlogsIdRoute: BlogsIdRoute,
  BlogsNewRoute: BlogsNewRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CareersListingsIdRoute: CareersListingsIdRoute,
  CareersListingsNewRoute: CareersListingsNewRoute,
  CareersSeasonsSeasonRoute: CareersSeasonsSeasonRoute,
  CareersListingsIndexRoute: CareersListingsIndexRoute,
  CareersSeasonsIndexRoute: CareersSeasonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
